<?php
// Chạy CLI để tạo SQL dùng trong phpMyAdmin; không mở endpoint seed công khai.
if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit();
}
$products = require __DIR__ . '/seed_products.php';
function sqlText(string $value): string
{
    return "'" . str_replace("'", "''", $value) . "'";
}
$sql = "-- Generated by: php database/export_seed.php\n";
$sql .= "-- Chọn database đã cài đặt trong phpMyAdmin rồi Import file này.\n";
$sql .= "-- Chỉ thêm món còn thiếu theo tên, không sửa giá, trạng thái hoặc đơn hàng cũ.\n";
$sql .= "SET NAMES utf8mb4;\nSTART TRANSACTION;\n";
foreach (array_unique(array_column($products, 'category')) as $category) {
    $name = sqlText($category);
    $sql .= "INSERT INTO categories(name) SELECT $name WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name=$name);\n";
}
foreach ($products as $product) {
    $values = [];
    foreach (['name', 'description', 'price', 'color', 'fruit', 'tag', 'type'] as $key) {
        $values[] = is_int($product[$key]) ? $product[$key] : sqlText($product[$key]);
    }
    $category = sqlText($product['category']);
    $name = sqlText($product['name']);
    $sql .=
        'INSERT INTO products(category_id,name,description,price,color,fruit,tag,type) SELECT c.id,';
    $sql .= implode(',', $values);
    $sql .= " FROM categories c WHERE c.name=$category AND NOT EXISTS (SELECT 1 FROM products WHERE name=$name);\n";
}
$sql .= "COMMIT;\n";
file_put_contents(__DIR__ . '/seed_products.sql', $sql);
echo 'Đã tạo database/seed_products.sql (' . count($products) . " món mẫu).\n";
