CREATE TABLE IF NOT EXISTS users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('customer','admin') NOT NULL DEFAULT 'customer',
 active TINYINT NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS categories (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE,
 active TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS products (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 category_id INT UNSIGNED NOT NULL,
 name VARCHAR(120) NOT NULL,
 description VARCHAR(500) NOT NULL,
 price INT UNSIGNED NOT NULL,
 color CHAR(7) NOT NULL DEFAULT '#f8d6a0',
 fruit VARCHAR(20) NOT NULL DEFAULT '🍑',
 tag VARCHAR(40) NOT NULL DEFAULT 'MÓN NGON',
 type VARCHAR(20) NOT NULL DEFAULT 'peach',
 active TINYINT NOT NULL DEFAULT 1,
 FOREIGN KEY (category_id) REFERENCES categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS toppings (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE,
 price INT UNSIGNED NOT NULL DEFAULT 7000,
 active TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS vouchers (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 code VARCHAR(24) NOT NULL UNIQUE,
 kind ENUM('fixed','percent') NOT NULL,
 value INT UNSIGNED NOT NULL,
 min_total INT UNSIGNED NOT NULL DEFAULT 0,
 expires_on DATE NOT NULL,
 max_uses INT UNSIGNED NOT NULL DEFAULT 100,
 used_count INT UNSIGNED NOT NULL DEFAULT 0,
 active TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS orders (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 code VARCHAR(30) NOT NULL UNIQUE,
 checkout_token CHAR(64) NOT NULL UNIQUE,
 user_id INT UNSIGNED NOT NULL,
 recipient_name VARCHAR(100) NOT NULL,
 phone VARCHAR(16) NOT NULL,
 address VARCHAR(500) NOT NULL,
 subtotal INT UNSIGNED NOT NULL,
 discount INT UNSIGNED NOT NULL DEFAULT 0,
 shipping_fee INT UNSIGNED NOT NULL,
 total INT UNSIGNED NOT NULL,
 voucher_code VARCHAR(24) DEFAULT NULL,
 status ENUM('pending','preparing','shipping','completed','cancelled') NOT NULL DEFAULT 'pending',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX (user_id, created_at),
 INDEX (status, created_at),
 FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS order_items (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id INT UNSIGNED NOT NULL,
 product_id INT UNSIGNED NOT NULL,
 product_name VARCHAR(120) NOT NULL,
 options_json TEXT NOT NULL,
 unit_price INT UNSIGNED NOT NULL,
 quantity INT UNSIGNED NOT NULL,
 FOREIGN KEY (order_id) REFERENCES orders(id),
 FOREIGN KEY (product_id) REFERENCES products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS reviews (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id INT UNSIGNED NOT NULL,
 product_id INT UNSIGNED NOT NULL,
 rating TINYINT UNSIGNED NOT NULL,
 comment VARCHAR(1000) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY (user_id, product_id),
 FOREIGN KEY (user_id) REFERENCES users(id),
 FOREIGN KEY (product_id) REFERENCES products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
