<?php

declare(strict_types=1);

return [
    1 => [
        'id' => 1,
        'name' => 'Trà đào cam sả',
        'description' => 'Đào ngọt dịu · Cam vàng · Sả thơm',
        'price' => 45000,
        'category' => 'Trà trái cây',
        'color' => '#f8d6a0',
        'fruit' => '🍑',
        'tag' => 'BEST SELLER',
        'type' => 'peach',
    ],
    2 => [
        'id' => 2,
        'name' => 'Trà dâu hibiscus',
        'description' => 'Dâu tươi · Trà hoa · Chút chua thanh',
        'price' => 49000,
        'category' => 'Trà trái cây',
        'color' => '#efadb1',
        'fruit' => '🍓',
        'tag' => 'ĐƯỢC YÊU THÍCH',
        'type' => 'berry',
    ],
    3 => [
        'id' => 3,
        'name' => 'Trà vải hoa nhài',
        'description' => 'Vải mọng · Nhài thơm · Vị thanh nhẹ',
        'price' => 45000,
        'category' => 'Trà hoa',
        'color' => '#d9e7b8',
        'fruit' => '🌿',
        'tag' => 'THANH MÁT',
        'type' => 'lychee',
    ],
    4 => [
        'id' => 4,
        'name' => 'Trà xoài nhiệt đới',
        'description' => 'Xoài chín · Chanh dây · Nắng mùa hè',
        'price' => 49000,
        'category' => 'Trà trái cây',
        'color' => '#f6da78',
        'fruit' => '🥭',
        'tag' => 'MÓN MỚI',
        'type' => 'mango',
    ],
    5 => [
        'id' => 5,
        'name' => 'Trà chanh bạc hà',
        'description' => 'Chanh tươi · Bạc hà · Trà xanh',
        'price' => 39000,
        'category' => 'Trà nguyên bản',
        'color' => '#d5df9e',
        'fruit' => '🍋',
        'tag' => 'NHẸ NHÀNG',
        'type' => 'lychee',
    ],
    6 => [
        'id' => 6,
        'name' => 'Trà cam mật ong',
        'description' => 'Cam vàng · Mật ong · Trà đen',
        'price' => 45000,
        'category' => 'Trà nguyên bản',
        'color' => '#efc194',
        'fruit' => '🍊',
        'tag' => 'TỰ NHIÊN',
        'type' => 'peach',
    ],
    7 => [
        'id' => 7,
        'name' => 'Trà ổi hồng',
        'description' => 'Ổi hồng · Trà nhài · Vị chua dịu',
        'price' => 45000,
        'category' => 'Trà trái cây',
        'color' => '#efb7bc',
        'fruit' => '🍈',
        'tag' => 'THƠM DỊU',
        'type' => 'berry',
    ],
    8 => [
        'id' => 8,
        'name' => 'Trà chanh dây dứa',
        'description' => 'Chanh dây · Dứa chín · Trà đen',
        'price' => 45000,
        'category' => 'Trà trái cây',
        'color' => '#f4d478',
        'fruit' => '🍍',
        'tag' => 'NHIỆT ĐỚI',
        'type' => 'mango',
    ],
    9 => [
        'id' => 9,
        'name' => 'Trà táo xanh',
        'description' => 'Táo xanh · Trà xanh · Chua thanh',
        'price' => 45000,
        'category' => 'Trà trái cây',
        'color' => '#d4e5a6',
        'fruit' => '🍏',
        'tag' => 'THANH MÁT',
        'type' => 'lychee',
    ],
    10 => [
        'id' => 10,
        'name' => 'Trà nho đen',
        'description' => 'Nho đen · Trà ô long · Vị ngọt nhẹ',
        'price' => 49000,
        'category' => 'Trà trái cây',
        'color' => '#d3afd6',
        'fruit' => '🍇',
        'tag' => 'ĐẬM VỊ',
        'type' => 'berry',
    ],
    11 => [
        'id' => 11,
        'name' => 'Trà thanh long đỏ',
        'description' => 'Thanh long đỏ · Trà nhài · Chanh tươi',
        'price' => 45000,
        'category' => 'Trà trái cây',
        'color' => '#efa7c5',
        'fruit' => '🌺',
        'tag' => 'RỰC RỠ',
        'type' => 'berry',
    ],
    12 => [
        'id' => 12,
        'name' => 'Trà dưa hấu bạc hà',
        'description' => 'Dưa hấu · Bạc hà · Trà xanh',
        'price' => 45000,
        'category' => 'Trà trái cây',
        'color' => '#f1b0ab',
        'fruit' => '🍉',
        'tag' => 'MÁT LẠNH',
        'type' => 'berry',
    ],
    13 => [
        'id' => 13,
        'name' => 'Trà quýt gừng',
        'description' => 'Quýt tươi · Gừng · Trà đen',
        'price' => 45000,
        'category' => 'Trà trái cây',
        'color' => '#efc082',
        'fruit' => '🍊',
        'tag' => 'THƠM ẤM',
        'type' => 'peach',
    ],
    14 => [
        'id' => 14,
        'name' => 'Trà kiwi chanh vàng',
        'description' => 'Kiwi · Chanh vàng · Trà nhài',
        'price' => 49000,
        'category' => 'Trà trái cây',
        'color' => '#c5df9e',
        'fruit' => '🥝',
        'tag' => 'TƯƠI MỚI',
        'type' => 'lychee',
    ],
    15 => [
        'id' => 15,
        'name' => 'Trà mận đỏ',
        'description' => 'Mận chín · Trà đen · Vị chua ngọt',
        'price' => 49000,
        'category' => 'Trà trái cây',
        'color' => '#dca4ae',
        'fruit' => '🍒',
        'tag' => 'CHUA NGỌT',
        'type' => 'berry',
    ],
    16 => [
        'id' => 16,
        'name' => 'Trà lê hoa cúc',
        'description' => 'Lê giòn · Hoa cúc · Vị thanh nhẹ',
        'price' => 45000,
        'category' => 'Trà hoa',
        'color' => '#eee0a9',
        'fruit' => '🍐',
        'tag' => 'DỊU NHẸ',
        'type' => 'lychee',
    ],
    17 => [
        'id' => 17,
        'name' => 'Trà sen nhãn',
        'description' => 'Nhãn · Trà sen · Hương thơm dịu',
        'price' => 49000,
        'category' => 'Trà hoa',
        'color' => '#ead5ac',
        'fruit' => '🌸',
        'tag' => 'HƯƠNG SEN',
        'type' => 'peach',
    ],
    18 => [
        'id' => 18,
        'name' => 'Trà hồng hoa dâu',
        'description' => 'Hoa hồng · Dâu tươi · Trà đen',
        'price' => 49000,
        'category' => 'Trà hoa',
        'color' => '#edbcc9',
        'fruit' => '🌹',
        'tag' => 'THƠM HOA',
        'type' => 'berry',
    ],
    19 => [
        'id' => 19,
        'name' => 'Trà hoa cúc mật ong',
        'description' => 'Hoa cúc · Mật ong · Ngọt dịu',
        'price' => 39000,
        'category' => 'Trà hoa',
        'color' => '#f1dfa0',
        'fruit' => '🌼',
        'tag' => 'NHẸ NHÀNG',
        'type' => 'mango',
    ],
    20 => [
        'id' => 20,
        'name' => 'Trà nhài thanh khiết',
        'description' => 'Trà nhài · Hương hoa · Hậu ngọt',
        'price' => 35000,
        'category' => 'Trà nguyên bản',
        'color' => '#dce4bb',
        'fruit' => '🌿',
        'tag' => 'NGUYÊN BẢN',
        'type' => 'lychee',
    ],
    21 => [
        'id' => 21,
        'name' => 'Trà ô long rang',
        'description' => 'Ô long rang · Hương ấm · Hậu thanh',
        'price' => 35000,
        'category' => 'Trà nguyên bản',
        'color' => '#dfc298',
        'fruit' => '🍂',
        'tag' => 'ĐẬM TRÀ',
        'type' => 'peach',
    ],
    22 => [
        'id' => 22,
        'name' => 'Hồng trà nguyên lá',
        'description' => 'Hồng trà · Hương thơm đậm · Ít chát',
        'price' => 35000,
        'category' => 'Trà nguyên bản',
        'color' => '#dfb18b',
        'fruit' => '🍃',
        'tag' => 'TRUYỀN THỐNG',
        'type' => 'peach',
    ],
    23 => [
        'id' => 23,
        'name' => 'Trà xanh mật ong',
        'description' => 'Trà xanh · Mật ong · Hậu dịu',
        'price' => 39000,
        'category' => 'Trà nguyên bản',
        'color' => '#d8dfac',
        'fruit' => '🍯',
        'tag' => 'THANH NHẸ',
        'type' => 'lychee',
    ],
    24 => [
        'id' => 24,
        'name' => 'Trà ô long chanh vàng',
        'description' => 'Ô long · Chanh vàng · Hương tươi',
        'price' => 39000,
        'category' => 'Trà nguyên bản',
        'color' => '#e8d9a1',
        'fruit' => '🍋',
        'tag' => 'TƯƠI MÁT',
        'type' => 'mango',
    ],
];
