<?php

declare(strict_types=1);

return [
    1 => [
        'id' => 1,
        'name' => 'Trà đào cam sả',
        'description' => 'Đào ngọt dịu · Cam vàng · Sả thơm',
        'price' => 45000,
        'category' => 'Trà trái cây',
        'color' => '#f8d6a0',
        'fruit' => '🍑',
        'tag' => 'BEST SELLER',
        'type' => 'peach',
    ],
    2 => [
        'id' => 2,
        'name' => 'Trà dâu hibiscus',
        'description' => 'Dâu tươi · Trà hoa · Chút chua thanh',
        'price' => 49000,
        'category' => 'Trà trái cây',
        'color' => '#efadb1',
        'fruit' => '🍓',
        'tag' => 'ĐƯỢC YÊU THÍCH',
        'type' => 'berry',
    ],
    3 => [
        'id' => 3,
        'name' => 'Trà vải hoa nhài',
        'description' => 'Vải mọng · Nhài thơm · Vị thanh nhẹ',
        'price' => 45000,
        'category' => 'Trà hoa',
        'color' => '#d9e7b8',
        'fruit' => '🌿',
        'tag' => 'THANH MÁT',
        'type' => 'lychee',
    ],
    4 => [
        'id' => 4,
        'name' => 'Trà xoài nhiệt đới',
        'description' => 'Xoài chín · Chanh dây · Nắng mùa hè',
        'price' => 49000,
        'category' => 'Trà trái cây',
        'color' => '#f6da78',
        'fruit' => '🥭',
        'tag' => 'MÓN MỚI',
        'type' => 'mango',
    ],
    5 => [
        'id' => 5,
        'name' => 'Trà chanh bạc hà',
        'description' => 'Chanh tươi · Bạc hà · Trà xanh',
        'price' => 39000,
        'category' => 'Trà nguyên bản',
        'color' => '#d5df9e',
        'fruit' => '🍋',
        'tag' => 'NHẸ NHÀNG',
        'type' => 'lychee',
    ],
    6 => [
        'id' => 6,
        'name' => 'Trà cam mật ong',
        'description' => 'Cam vàng · Mật ong · Trà đen',
        'price' => 45000,
        'category' => 'Trà nguyên bản',
        'color' => '#efc194',
        'fruit' => '🍊',
        'tag' => 'TỰ NHIÊN',
        'type' => 'peach',
    ],
];
